"""check

Revision ID: 4b8ce2ee55a4
Revises: c6d5f6004879
Create Date: 2024-05-22 23:03:53.953415

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4b8ce2ee55a4"
down_revision: Union[str, None] = "c6d5f6004879"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
