"""balance

Revision ID: 4f84e6d21e95
Revises: 846d25b63cfa
Create Date: 2024-05-24 18:57:11.833547

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4f84e6d21e95"
down_revision: Union[str, None] = "846d25b63cfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
