"""balance

Revision ID: 846d25b63cfa
Revises: 15e842d64256
Create Date: 2024-05-24 18:48:24.758841

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "846d25b63cfa"
down_revision: Union[str, None] = "15e842d64256"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
